# раскладки us,ru переключаются Alt+Shift
input {
    kb_layout = us,ru
    kb_options = grp:alt_shift_toggle,grp:lalt_lshift_toggle
    sensitivity = 0
    follow_mouse = 1
    repeat_rate = 25
    repeat_delay = 600
    left_handed = false
    natural_scroll = false
    mouse_refocus = true
    float_switch_override_focus = 1
    touchpad {
        disable_while_typing = true
        natural_scroll = true
        middle_button_emulation = false
        clickfinger_behavior = true
        tap-to-click = true
        tap-and-drag = true
        tap_button_map = lrm
        scroll_factor = 1.0
    }
}

gesture = 3, horizontal, workspace
